### ISSUE TITLE
Port to Python3

### ISSUE THREAD

**Issue by taranarmo** [jonasstein/scanaerial#26]
Hi, I've decided to try Futurize python script on scanaerial and it seems successful. Now the code in my fork could be run in python2 of python3. I had only install python2-future and python2-configparser packages to run updated code on python2 (maybe these packages should be added in library-check.py).

Should I consider making Pull request?

**Comment by jonasstein** [comment]
At first **thank you very much** for your work on this project. I think it is very good to overhaul the source and bring it to the next decade of python. 
**I even would say we can drop Python 2 support completely and go with pure Python 3. Any comments?** 
I had a look at your changes. I would prefer `x*1.0/y` for the divisions. (see also https://www.python.org/dev/peps/pep-0238/)
I want to ask other users and contributors about their opinion on this too. Just write your comments here.

**Comment by taranarmo** [comment]
As I mentioned, I didn't do anything with code myself, I just ran Futurize script on it.
I do not have much experience in (relatively) large projects, so porting scanaerial would be nice skill gain :)

**Comment by ZeLonewolf** [comment]
Unfortunately python2 is now end of life, and so scanaerial no longer runs.
To force it to run I changed line 122:
WAY_TAGS = dict(WAY_TAGS.items() + config.items('TAGS'))
to
WAY_TAGS = dict(WAY_TAGS.items() | config.items('TAGS'))

Which seems to make it run in python3.

**Comment by taranarmo** [comment]
I made more commits to my fork and created [pull request](https://github.com/jonasstein/scanaerial/pull/27)

**Comment by jonasstein** [comment]
anything left to do here?

**Comment by taranarmo** [comment]
Probably not, now I don't see any warnings and code runs fine on my machine with Python 3.10.10
