### ISSUE TITLE
Scanaerial can't handle internet connections through a HTTP-Proxy

### ISSUE THREAD

**Issue by kerosin** [jonasstein/scanaerial#5]
Scanaerial doesn't care about Proxy-Settings made in JOSM. You get a connection timeout error when running scanaerial on a internet connection via http-proxy.

Would be nice to integrate this in a further status!

**Comment by jonasstein** [comment]
does a SOCKS Proxy with ssh as workaround help?

**Comment by Vort** [comment]
It may also worth try to wrap ```scanaerial.py``` call with ```.bat```/```.sh``` file, which sets ```http_proxy``` environment variable:
https://stackoverflow.com/a/17248931
